# Generated by Django 5.2.10 on 2026-03-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_alter_teammember_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='bio',
            field=models.TextField(blank=True, help_text='Short introduction/bio (especially for faculty)'),
        ),
    ]
